version: '0.0.1'

services:
  app-dev:
    container_name: movie-dev
    working_dir: /root
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    volumes:
      - "./:/root"
    environment:
      - SERVER_TYPE=development
      - BASE_URL=${BASE_URL}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - DASHBOARD_URL=${DEV_DASHBOARD_URL}

  app-pro:
    container_name: movie-pro
    build:
      context: .
      target: pro
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVER_TYPE=production
      - BASE_URL=${BASE_URL}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - DASHBOARD_URL=${DASHBOARD_URL}
