version: '0.0.1'

services:
  app:
    working_dir: /root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - "./:/root"