version: '0.0.1'

services:
  app-dev:
    working_dir: /app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./:root/"
    environment:
      - SERVER_TYPE=development

  app-pro:
    build:
      context: .
      target: pro
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVER_TYPE=production