version: '0.0.1'

services:
  app-dev:
    container_name: movie-dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    environment:
      - SERVER_TYPE=development
      - BASE_URL=${BASE_URL}

  app-pro:
    container_name: movie-pro
    build:
      context: .
      target: pro
      dockerfile: Dockerfile
    ports:
      - "6789:6789"
    environment:
      - SERVER_TYPE=production
      - BASE_URL=${BASE_URL}
